// Generated by dts-bundle-generator v7.2.0

declare abstract class EmEnum {
	protected constructor();
	/** @internal */
	value: number;
}
/**
 * VADParameter constants correspond to different Voice Activity Detection
 * parameters that are used for endpointing during recognition. You can change
 * values of these parameters using {@link KeenASR.setVADParameters | setVADParameters} method.
 */
export class VADParameter extends EmEnum {
	private readonly _brand: VADParameter;
	/**
	 * Timeout after this many seconds even if nothing has been recognized. Default is 10 seconds.
	 */
	static readonly timeoutForNoSpeech: VADParameter;
	/**
	 * Timeout after this many seconds if we had a good (high probability) match to the final
	 * state. Default is 1 second.
	 */
	static readonly timeoutEndSilenceForGoodMatch: VADParameter;
	/**
	 * Timeout after this many seconds if we had any match (even if final state has not been reached).
	 * Default is 2 seconds.
	 */
	static readonly timeoutEndSilenceForAnyMatch: VADParameter;
	/**
	 * Timeout after this many seconds regardless of what has been recognized.
	 * This is effectively upper bound on the duration of recognition. Default value is 20 seconds.
	 */
	static readonly timeoutMaxDuration: VADParameter;
}
/**
 * SpeakingTask defines a type of speaking task that will be handled. It is primarily
 * used to indicate to methods that create decoding graphs what type of task they need
 * to handle, so that appropiate customization can be done when creating language model
 * and decoding graph.
 */
export class SpeakingTask extends EmEnum {
	private readonly _brand: SpeakingTask;
	/**
	 * Default task (no prior knowledge exists about the type of spoken interaction).
	 */
	static readonly DEFAULT: SpeakingTask;
	/**
	 * Reading aloud in educational context (children, language learning).
	 */
	static readonly ORAL_READING: SpeakingTask;
}
/**
 * These constants indicate different states recognizer can assume.
 */
export class RecognizerState extends EmEnum {
	private readonly _brand: RecognizerState;
	/**
	 * Recognizer is initialized but it needs decoding graph before it can start listening.
	 */
	static readonly NEEDS_DECODING_GRAPH: RecognizerState;
	/**
	 * Recognizer is ready to start listening.
	 */
	static readonly READY_TO_LISTEN: RecognizerState;
	/**
	 * Recognizer is actively listening. Any calls to {@link KeenASR.startListening | startListening}
	 * will be ignored.
	 */
	static readonly LISTENING: RecognizerState;
	/**
	 * Recognizer is not acquiring incoming audio any more, it is computing the final result.
	 * Recognizer is not likely to be in this state for a long time; approximately 100-300ms,
	 * depending on the device and the CPU speed.
	 */
	static readonly FINAL_PROCESSING: RecognizerState;
}
/**
 * LogLevel defines logging levels used by the SDK.
 *
 * Meant to be used with the {@link KeenASR.setLogLevel} method.
 */
export class LogLevel extends EmEnum {
	private readonly _brand: LogLevel;
	/**
	 * Log debug messages and higher.
	 */
	static readonly DEBUG: LogLevel;
	/**
	 * Log info messages and higher.
	 */
	static readonly INFO: LogLevel;
	/**
	 * Log only warnings or errors (default level).
	 */
	static readonly WARNING: LogLevel;
}
/**
 * Initialization parameters.
 * @inline
 */
export type InitParams = {
	/**
	 * The full URL of the ASR bundle (e.g., `https://.../bundle-name.tgz`). The bundle
	 * needs to be in a tar gzipped file, and your web server needs to be configured to serve
	 * these files with Content-Encoding set to gzip. For more details, see
	 * {@link https://keenresearch.com/keenasr-docs/keenasr-web-installation.html | SDK Installation} docs.
	 */
	asrBundleURL: string | URL;
	/**
	 * Whether to enable echo cancellation for audio input. Defaults to `false`.
	 */
	doEchoCancellation?: boolean;
	/**
	 * Callback invoked when the core module is ready.
	 *
	 * Can be used for e.g. initializing KeenASR logging or reporting initialization progress in the UI.
	 */
	onCoreReady?: () => void;
	/**
	 * Callback invoked when the ASR bundle is ready (dowloaded and stored in the local filesystem).
	 *
	 * Can be used for reporting initialization progress in the UI.
	 */
	onASRBundleReady?: () => void;
};
/**
 * <p>
 * {@link WordPronunciation} is a class that defines a mapping between a <i>word</i> and its phonetic <i>pronunciation</i>.
 * A phonetic <i>pronunciation</i> is a space separated string of <i>phonemes</i> that define how the <i>word</i> is
 * pronounced. The names of the <i>phonemes</i> are language-specific and defined in the ASR Bundle. For some languages,
 * where this mapping is not deterministic, the <i>ASR Bundle</i> will contain a large lookup table in the <i>lang/lexicon.txt</i> file.
 * </p>
 * <p>
 * You can use {@link WordPronunciation} to provide alternatives to existing <i>pronunciations</i>, or to define pronunciations for
 * words that are not in the ASR Bundle lexicon. Some scenarios where this could be useful is modeling of: a) <b>made-up words</b>,
 * b) <b>common mispronunciations</b>. The latter can be useful in use cases involving language learning and reading instruction.
 * In those scenarios you can also provide an arbitrary <i>tag</i> value when constructing a WordPronunciation. The <i>tag</i> will be appended
 * to the recognized <i>word</i> in the result, if such pronunciation was the most likely hypothesis. For example, given a <i>word</i> “<b>PEAK</b>”
 * and <i>tag</i> “<b>WRONG</b>” the word in the result will be “<b>PEAK#WRONG</b>”.
 * </p>
 * <p>
 * Example: a <i>pronunciation</i> for <i>PEAK</i> that could potentially be tagged as <i>WRONG</i> is
 * </p>
 * <pre>
 * let wordPronunciation = new WordPronunciation("PEAK", "B IY1 K", "WRONG");
 * </pre>
 */
export declare class WordPronunciation {
	/**
	 * <p>
	 * The <i>string</i> specifying the <i>word</i>.
	 * </p>
	 * <p>
	 * Example: "<i>CAT</i>".
	 * </p>
	 */
	readonly word: string;
	/**
	 * <p>
	 * The phonetic transcription of a <i>word</i>, provided as a space-separated sequence of <i>phones</i>.
	 * </p>
	 */
	readonly pronunciation: string;
	/**
	 * <p>
	 * The optional <i>tag</i> value.
	 * </p>
	 * <p>
	 * When provided during construction, this <i>tag</i> will be appended together with the <i>#</i> symbol to the <i>word</i> if the variation of
	 * the <i>word</i> with the provided <i>pronunciation</i> is recognized. For example, <i>PEAK#WRONG</i>.
	 * </p>
	 */
	readonly tag: string;
	/**
	 * <p>
	 * Is this object is valid, for a given {@link Recognizer}.
	 * </p>
	 * <p>
	 * A <i>word pronunciation</i> is valid if:
	 * </p>
	 * <ol>
	 * <li><i>word</i> does not contain <i>&lt;</i> or <i>&gt;</i> characters.</li>
	 * <li><i>tag</i> is not equal to "<i>INC</i>" (a reserved <i>tag</i>) and it does not contain a <i>#</i> character.</li>
	 * <li><i>pronunciation</i> is composed of valid <i>phones</i> (as defined in the <i>ASR Bundle</i> that was used to initialize the {@link Recognizer}).</li>
	 * </ol>
	 */
	readonly isValid: boolean;
	/**
	 * <p>
	 * Parameterized constructor.
	 * </p>
	 * <p>
	 * <b>NOTE:</b> both <i>word</i> and <i>phones</i> will internally be stored in uppercase.
	 * </p>
	 *
	 * @param word string specifying the <i>word</i>. For example "<i>CAT</i>".
	 * @param pronunciation a space separated <i>phone</i> string.
	 * @param tag a <i>tag</i> suffix for the <i>word</i>.
	 * @throws Error when the SDK (i.e. Recognizer) is not initialized
	 */
	constructor(word: string, pronunciation: string, tag?: string);
}
/**
 * <p>
 * {@link AudioQualityResult} interface contains various metrics for audio quality estimation,
 * returned as part of the Response, including Signal to Noise Ratio (SNR) and various signal level metrics.
 * </p>
 */
export interface AudioQualityResult {
	/**
	 * <p>
	 * Root mean square (RMS) values for each frame (25<i>ms</i> long with 10<i>ms</i> shift) in decibels in the processed audio.
	 * Values are computed as 20·log<sub>10</sub>( √( Σ(sample value)<sup>2</sup> ) ).
	 * Where a frame has a zero signal level, the RMS <i>dB</i> value is reported as around -100<i>dB</i>.
	 * </p>
	 */
	frameRmsValues: number[];
	/**
	 * <p>
	 * The number of raw samples in processed audio that were clipped (values outside of a clipping window defining a maximum and minimum threshold).
	 * Clipping indicates that the user might be too close to the microphone during audio capture or fidgeting
	 * with the microphone. Clipped samples can have negative impact on speech recognition performance.
	 * </p>
	 */
	clippedSampleCount: number;
	/**
	 * <p>
	 * The estimated signal to noise ratio (SNR) in decibels for the processed audio.
	 * SNR is computed as the difference between mean speech RMS value and mean noise RMS value.
	 * SNR accounts for some transient noise but primarily models it does stationary background noise.
	 * Low values of SNR have negative impact on speech recognition performance.
	 * </p>
	 * <p>
	 * <b>NOTE:</b> SNR value will be <i>null</i> if there isn't sufficient data to compute it.
	 * </p>
	 */
	snrValue: number;
	/**
	 * <p>
	 * The mean frame root mean square (RMS) decibel level for the speech segments in the processed audio.
	 * </p>
	 * <p>
	 * <b>NOTE:</b> This value will be <i>null</i> if no speech segments were available in the response.
	 * </p>
	 */
	meanSpeechRmsValue: number;
	/**
	 * <p>
	 * The mean frame root mean square (RMS) decibel level for the non-speech segments (noise) in the processed audio.
	 * </p>
	 */
	meanNonSpeechRmsValue: number;
	/**
	 * <p>
	 * The estimated peak root mean square (RMS) decibel level of speech in the processed audio.
	 * This value is computed as the 98<i>th</i> percentile of all the RMS speech levels, to filter outliers.
	 * Low values would indicate faint speech or the user being too far from the microphone.
	 * This metric may not work well for responses with very short speech segments.
	 * </p>
	 * <p>
	 * <b>NOTE:</b> This value will be <i>null</i> if no speech segments were available in the response.
	 * </p>
	 */
	peakSpeechRmsValue: number;
	/**
	 * <p>
	 * A flag indicating that a high root mean square (RMS) value was detected during the initial part of the processed audio.
	 * This could indicate that:
	 * </p>
	 * <ol>
	 * <li>The device is playing audio (which is captured by the microphone).</li>
	 * <li>The user began speaking earlier than expected (and recognizer started to listen too late).</li>
	 * <li>There are high levels of noise, in general.</li>
	 * </ol>
	 */
	initialSegmentRmsWarning: boolean;
}
/**
 * @inline
 */
export interface DecodingGraphConfig {
	/**
	 * an optional array of {@link WordPronunciation} objects specifying
	 * alternative pronunciation for the words, and (optional) tags that can be used to identify
	 * those pronunciations. If these specific pronunciations were recognized, these words will
	 * be reported in partial/final result with #tag tag appended to the word (e.g. CHOICE#WRONG,
	 * if WRONG was a tag).
	 */
	altProns?: WordPronunciation[];
	/**
	 * one of {@link SpeakingTask} specifying a type of interaction.
	 */
	speakingTaskType: SpeakingTask;
	/**
	 * an optional value that defines a <SPOKEN_NOISE> probability value. The value will be
	 * clipped to [0-1] range. Value close to 0 will tune down the probability of recognizing
	 * <SPOKEN_NOISE>. Value close to 1 will make <SPOKEN_NOISE> recognition as likely as any other word.
	 */
	spokenNoiseProb?: number;
}
declare abstract class KeenASRBase {
	protected startCoreListening(): void;
	protected stopCoreListening(): void;
	/**
	 * @inheritDoc SpeakingTask
	 * @category DECODING GRAPH
	 */
	get SpeakingTask(): typeof SpeakingTask;
	/**
	 * @inheritDoc LogLevel
	 * @category CONFIGURATION
	 */
	get LogLevel(): typeof LogLevel;
	/**
	 * @returns The version of the SDK.
	 * @category VERSION
	 */
	version(): string;
	/**
	 * @returns The git commit hash of the current build.
	 * @category VERSION
	 */
	getVersionHash(): string;
	/**
	 * Fetch the ASR bundle from the given URL.
	 * @param bundleURL - bundle URL
	 * @returns - bundle object as a byte array.
	 */
	protected abstract fetchASRBundle(bundleURL: string | URL): Promise<Uint8Array>;
	/**
	 * Initialize the SDK with a bundle URL and options (e.g. perform echo cancellation).
	 * @param params - initialization parameters.
	 * @category INITIALIZATION
	 */
	initialize({ asrBundleURL, doEchoCancellation, onCoreReady, onASRBundleReady, }: InitParams): Promise<void>;
	/**
	 * @param sampleRate
	 * @param doEchoCancellation
	 */
	protected abstract initAudioController(sampleRate: number, doEchoCancellation: boolean): Promise<void>;
	/**
	 * Callback invoked each time when a partial result is available. This callback will execute periodically
	 * while the recognizer is listening, and provide partial result (only text, without more detailed
	 * information like timing, phonemes, etc.).
	 *
	 * @category LISTENING
	 * @category CONFIGURATION
	 */
	onPartialResult?: (result: ASRResult) => void;
	/**
	 * Callback invoked when the recognizer stops listening due to one of the {@link VADParameter} thresholds
	 * being met. The callback will provide an instance of {@link ASRResponse} object, which contains
	 * {@link ASRResult}, and various other data related to the most recent interaction. This include access
	 * to raw audio via {@link ASRResponse.getAudio}.
	 *
	 * @category LISTENING
	 * @category CONFIGURATION
	 */
	onFinalResponse?: (response: ASRResponse) => void;
	/**
	 * subclasses are not required to override
	 */
	protected stopAudioInput(): Promise<void>;
	/**
	 * Prepare for recognition by loading decoding graph that was created via one of the
	 * methods that create decoding graphs. Calls to this method will be ignored if the recognizer
	 * is listening.
	 *
	 * After calling this method, recognizer will load the decoding graph into memory and it
	 * will be ready to start listening via startListening method.
	 *
	 * @param decodingGraphName - name of the decoding graph.
	 * @param computeGop - set to true to compute Goodness of Pronunciation scores in the final
	 * result. There is additional overhead when computing these scores, and they require additional
	 * assets to be present in the ASR Bundle.
	 *
	 * @category LISTENING
	 */
	prepareForListeningWithDecodingGraphWithName(decodingGraphName: string, computeGop?: boolean): void;
	/**
	 * Prepare for recognition by loading contextual decoding graph that was prepared via
	 * ```ts
	 * KeenASR.createContextualDecodingGraphFromPhrases(phrases: string[][], altProns: WordPronunciation[], speakingTask: SpeakingTask, name: string)
	 * ```
	 * method. Calls to this method will be ignored if the recognizer is listening.
	 *
	 * After calling this method, recognizer will be ready to start listening via startListening method.
	 *
	 * @param decodingGraphName - name of the decoding graph.
	 * @param contextId - context identifier.
	 * @param computeGop - set to true if you would like Goodness of Pronunciation scores to be computed
	 * in the final result. There is additional overhead when computing these scores, and they require
	 * additional assets to be present in the ASR Bundle.
	 *
	 * @category LISTENING
	 */
	prepareForListeningWithContextualDecodingGraphWithNameAndContextId(decodingGraphName: string, contextId: number, computeGop?: boolean): void;
	/**
	 * Returns recognizer state, one of {@link RecognizerState} values.
	 * @returns state of the recognizer, one of {@link RecognizerState} values.
	 */
	getRecognizerState(): RecognizerState;
	/**
	 * Set any of {@link VADParameter} Voice Activity Detection parameters. These parameters can be
	 * set at any time and they will go into effect immediately.
	 *
	 * @param parameters - a combination of Voice Activity Detection parameters and their corresponding values.
	 *
	 * @category CONFIGURATION
	 */
	setVADParameters(parameters: {
		[K in keyof Omit<typeof VADParameter, "prototype">]?: number;
	}): void;
	/**
	 * VAD (voice activity detection) gating introduces a super lightweight voice activity
	 * detection before speech recognition. After you call startListening method, if VADGating is
	 * turned on recognition will start only after voice was detected by VADGating module. You would
	 * typically use this only in always-on listening scenarios when you want to preserve battery life.
	 *
	 * @param value - true if VAD Gating should be turned on, false otherwise.
	 *
	 * @category CONFIGURATION
	 */
	setVADGating(value: boolean): void;
	/**
	 * Set the level of emitted logs by the SDK. Default is WARNING.
	 * @param logLevel - one of {@link LogLevel}.
	 *
	 * @category CONFIGURATION
	 */
	setLogLevel(logLevel: LogLevel): void;
	/**
	 * Create decoding graph from an array of phrases, for a specific task, using
	 * provided array of word mispronunciations and save it in the filesystem for later use.
	 *
	 * @param name - a name of the contextual decoding graph. All graph resources will be stored in the
	 * local file system, in a directory named DECODING_GRAPH_NAME-ASR_BUNDLE_NAME.
	 * @param phrases - an array of String objects that specify phrases recognizer should
	 * listen for. These phrases are used to create an ngram language model, from which decoding
	 * graph is created. Text in phrases should be normalized (e.g. numbers and dates should be
	 * represented by words, so 'two hundred dollars' not $200).
	 * @param config - configuration parameters. See {@link WordPronunciation} for how to construct valid alternative pronunciations.
	 * @return true if the decoding graph was created successfully; false otherwise.
	 *
	 * @category DECODING GRAPH
	 */
	createDecodingGraphFromPhrases(name: string, phrases: string[], config: DecodingGraphConfig): Promise<boolean>;
	/**
	 * Create decoding graph from an array of phrases, using specified triggerPhase, and save
	 * it in the filesystem for later use. Decoding graphs can be referenced by their name by
	 * various methods in the SDK. When using decoding graphs created with the trigger phrase
	 * support, upon calling StartListening method the SDK will listen continuously until it
	 * hears the trigger phrase; only then will partial results start occurring.
	 *
	 * @param name - a name of the contextual decoding graph. All graph resources will be stored in the
	 * local file system, in a directory named DECODING_GRAPH_NAME-ASR_BUNDLE_NAME.
	 * @param phrases - an array of String objects that specify phrases recognizer should listen for.
	 * These phrases are used to create an ngram language model, from which decoding graph is created.
	 * Text in phrases should be normalized (e.g. numbers and dates should be represented by words,
	 * so 'two hundred dollars' not $200).
	 * @param trigger_phrase - a String representing a trigger phrase used to initiate recognition when
	 * using this decoding graph, for example "Hey computer". When using decoding graph with trigger
	 * phrase, recognizer will continuously listen until it hears the trigger phrase. No partial
	 * callback results will be provided until trigger phrase is recognized.
	 * @param config - configuration parameters. See {@link WordPronunciation} for how to construct valid alternative pronunciations.
	 * @return true if the decoding graph was created successfully; false otherwise.
	 *
	 * @category DECODING GRAPH
	 */
	createDecodingGraphFromPhrasesWithTriggerPhrase(name: string, phrases: string[], trigger_phrase: string, config: DecodingGraphConfig): Promise<boolean>;
	/**
	 * Create contextual decoding graph from an array of contexts, for a specific task, using provided
	 * array of alterantive pronunciations, and save it in the filesystem for later use. Contextual
	 * decoding graphs can be referenced by their name by various methods in the SDK.
	 *
	 * @param name - a name of the contextual decoding graph. All graph resources will be stored in the
	 * local file system, in a directory named DECODING_GRAPH_NAME-ASR_BUNDLE_NAME.
	 * @param contexts - an array of contexts (where each context is an array of phrases).
	 * You can swtich between contexts via {@link KeenASR.prepareForListeningWithContextualDecodingGraphWithNameAndContextId},
	 * where `contextIds` are using 0-base indexing. These phrases are used to create an ngram language model,
	 * from which decoding graph is created. Text in phrases should be normalized (e.g. numbers and
	 * dates should be represented by words, so 'two hundred dollars' not $200).
	 * @param config - configuration parameters. See {@link WordPronunciation} for how to construct valid alternative pronunciations.
	 * @return true if the decoding graph was created successfully; false otherwise.
	 *
	 * @category DECODING GRAPH
	 */
	createContextualDecodingGraphFromPhrases(name: string, contexts: string[][], config: DecodingGraphConfig): Promise<boolean>;
	/**
	 * Returns true if valid decoding graph with the given name exists in the filesystem.
	 * @param name - name of the decoding graph.
	 * @returns - True if decoding graph with such name exists, false otherwise. This method
	 * will also check for existence of all the necessary files in the decoding graph directory.
	 *
	 * @category DECODING GRAPH
	 */
	decodingGraphWithNameExists(name: string): boolean;
	/**
	 * Mount the root of the emscripten file system
	 * @param mountPath - mount path.
	 */
	protected abstract mountAtRoot(mountPath: string): Promise<void>;
	/**
	 * Align reference and hypothesis(recognized) text
	 * @param refWords - reference words.
	 * @param hypWords - hypothesis words.
	 * @param useChardiff
	 * @param insertToken
	 * @returns
	 */
	alignTexts(refWords: string[], hypWords: string[], useChardiff: boolean, insertToken: string): {
		alignedRef: string[];
		alignedHyp: string[];
	};
}
/**
 * ASRPhone represents a phone (speech segment that possesses distinct physical or perceptual properties and serves as the basic unit of phonetic speech analysis). ASR Bundle used to initialize the recognizer will contain a list of phones that were used to train the models. In the context of KeenASR SDK, each recognized word is represented via ASRWord object, which will contain an array of ASRPhone object that correspond to the most likely phonetic transcription of the given word.
 */
export interface ASRPhone {
	/**
	 * Duration, in seconds, for this phone.
	 */
	duration: number;
	/**
	 * Pronunciation score in the range 0 to 1. Higher value corresponds to better native-like pronunciation. Scores are computed in reference to the recognizer word and its corresponding phonetic representation.
	 */
	pronunciationScore: number;
	/**
	 * Start time, in seconds, for this phone relative to when the recognizer started to listen.
	 */
	startTime: number;
	/**
	 * Text of the phone.
	 */
	text: string;
}
/**
 * ASRWord provides word text, timing information, and the confidence of the word.
 *
 * NOTE: that in certain circumstances startTime, duration, and confidence may be null.
 */
export interface ASRWord {
	/**
	 * Confidence in the range 0 to 1 for the word. Higher value corresponds to better confidence that the recognized text matches what was said.
	 */
	confidence: number;
	/**
	 * Duration, in seconds, for this word.
	 */
	duration: number;
	/**
	 * An array of ARSPhone objects that comprise this ASRWord.
	 */
	phones: ASRPhone[];
	/**
	 * Start time, in seconds, for this word relative to when the recognizer started to listen.
	 */
	startTime: number;
	/**
	 * Text of the word.
	 */
	text: string;
}
/**
 * ASRResult represents results of the recognition.
 */
export interface ASRResult {
	/**
	 * Recognition result clean text; all tokens of type &lt;TOKEN&gt; are removed (e.g. <SPOKEN_NOISE>, etc.)
	 */
	cleanText: string;
	/**
	 * Text of the recognition result.
	 */
	text: string;
	/**
	 * Overall confidence score in [0,1] range.
	 *
	 * NOTE: partial results do not have this value set.
	 */
	confidence: number;
	/**
	 * An Array of ARSRWord objects that comprise this result.
	 *
	 * NOTE: partial results do not have this value set.
	 */
	words: ASRWord[];
}
/**
 * ASRResponse contains various metadata related to the single interaction with the speech recognition system, from calling startListening until the recognizer stopped listening. It is provided to the application via onFinalResponse callback method.
 */
export interface ASRResponse {
	/**
	 * The bundleID/packageName of the app that created the response.
	 */
	appBundleId: string;
	/**
	 * The name of the ASR Bundle that was used initialize the recognizer.
	 */
	asrBundle: string;
	/**
	 * Final ASR result corresponding to this response.
	 */
	asrResult: ASRResult;
	/**
	 * the audio quality results that include rms values list, clipped sample count
	 * and estimated SNR value
	 */
	audioQualityResult: AudioQualityResult;
	/**
	 * BOOL value that’s set to true if echo cancellation was used during recognition of this response, or false if it wasn’t (the value is captured and persisted at the end of recognition).
	 */
	echoCancellation: boolean;
	/**
	 * Unique identifier of this response. This corresponds to the id set via startListening method.
	 */
	id: string;
	/**
	 * Version of KeenASR SDK.
	 */
	sdkVersion: string;
	/**
	 * LocalDateTime object that specifies the date/time when this response was created (in current device timezone).
	 */
	startTime: Date;
	/**
	 * Get the audio data as a File object (a named Blob).
	 *
	 * NOTE: that this method can only be called in the `onFinalResponse` callback.
	 * The audio data will be freed after the callback is executed, so it should be copied if needed.
	 * @return File object containing audio data.
	 */
	getAudio(): File;
}
/**
 * KeenASR class provides a high-level JavaScript module that provides core ASR functionality.
 *
 * Installation of the package is described
 *  {@link https://keenresearch.com/keenasr-docs/keenasr-web-installation.html | here}.
 *
 * Typically, you will follow these steps when using the SDK:
 *
 * 1. Initialize the SDK with {@link initialize} method.
 * 2. Configure recognizer options and callbacks. See Configuration category and {@link onPartialResult} and {@link onFinalResponse} callbacks.
 * 3. Create one or more decoding graphs See Decoding Graphs category for relevant methods.
 * 4. Prepare recognizer for listening with a specific graph. See Listening category for different prepareForListening methods.
 * 5. Call {@link startListening} to start audio capture and recognition. {@link partialResult} method will be called periodically and you can use it to display what has been recognized so far. {@link finalResponse} method will be called when the recognizer stops listening, and it will provide the {@link ASRResponse | final response}, which will include the final {@link ASRResult | result}.
 *
 * @hideconstructor
 */
export declare class KeenASR extends KeenASRBase {
	/**
	 * Get or set the audio input ID that will be matched against
	 * {@link MediaDeviceInfo.deviceId} to find the audio input device for recording.
	 *
	 * If the device with a specified ID is not found, then recording will fall
	 * back to the system default audio input device.
	 *
	 * @category MICROPHONE ACCESS
	 * @category CONFIGURATION
	 */
	audioInputDeviceId: string;
	private static _isSafariRegex;
	private static _isChromeRegex;
	private static _safariVersionRegex;
	private static _chromeVersionRegex;
	/**
	 * Filters the result of {@link navigator.mediaDevices.enumerateDevices} where {@link MediaDeviceInfo.kind kind} == `'audioinput'`
	 * @param requestIfNeeded - request microphone access if needed
	 * @param getAudioInputDeviceId - callback that returns audio input device id.
	 *
	 * @category MICROPHONE ACCESS
	 */
	getAvailableAudioInputs(requestIfNeeded?: boolean, getAudioInputDeviceId?: (audioInputDeviceId: string) => void): Promise<MediaDeviceInfo[]>;
	/**
	 * Starts audio capture with the default audio input and recognition of the incoming audio.
	 * Listening process will stop when either: a) there is an explicit call to the
	 * {@link stopListening} method, b) if one of the Voice Activity Detection thresholds has
	 * triggered (for example, end-silence); in this case {@link onFinalResponse} callback will
	 * be executed, whereas calling {@link stopListening} will not compute {@link ASRResponse | final response}.
	 *
	 * @category LISTENING
	 */
	startListening(): Promise<void>;
	/**
	 * Stop the recognizer from processing incoming audio and stops audio capture. You would
	 * typically use this method when you need to stop the recognizer as soon as possible
	 * (for example, because user is navigating away from the activity). If you use this method
	 * you will not be able to obtain the result for the current listening session.
	 *
	 * @category LISTENING
	 */
	stopListening(): Promise<void>;
	/**
	 * Status of whether the browser microphone permissions have been granted.
	 * Note: the navigator.permissions API will not work for 'microphone' in Firefox
	 *
	 * @category MICROPHONE ACCESS
	 */
	isMicrophoneAccessEnabled(): Promise<boolean>;
	/**
	 * Request microphone permissions from user.
	 * @param getAudioInputDeviceId - callback to get the audio input device id
	 *
	 * @category MICROPHONE ACCESS
	 */
	requestMicrophoneAccess(getAudioInputDeviceId?: (audioInputDeviceId: string) => void): Promise<void>;
	/**
	 * Check if the browswer can run keenasr-web library. Currently, only Chrome 113 (or higher) and Safari 18 (or higher) are supported.
	 * More specifically, this function checks if cross-origin isolation is enabled and whether web assembly is supported.
	 *
	 * Cross-origin isolation needs to be enabled for the use of SharedArrayBuffer by the Web SDK. This JavaScript object
	 * allows shared memory between web workers and the main thread. Although web workers run in the same process as the main thread,
	 * they have separate execution contexts and memory spaces, by default. For this reason, SharedArrayBuffer provides a way for
	 * different execution contexts to access the same memory buffer, enabling efficient and fast data exchange without copying.
	 *
	 * For SharedArrayBuffer browser compatibility visit this [page](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer#browser_compatibility).
	 *
	 * For WebAssembly browser compatibility visit this [page](https://developer.mozilla.org/en-US/docs/WebAssembly/Reference/JavaScript_interface#browser_compatibility).
	 *
	 * Cross-origin isolation is enabled via the following headers:
	 * ```
	 * Cross-Origin-Opener-Policy: same-origin
	 * Cross-Origin-Embedder-Policy: require-corp
	 * ```
	 *
	 *
	 *
	 * @returns true if browser can run keenasr-web library, false otherwise
	 *
	 * @category INITIALIZATION
	 */
	isBrowserSupported(): boolean;
	/**
	 * Platform-specific initializer
	 * @param sampleRate - sample rate.
	 * @param doEchoCancellation - perform echo cancellation.
	 */
	protected initAudioController(sampleRate: number, doEchoCancellation: boolean): Promise<void>;
	/**
	 * Must be overridden because Emscripten FS types need the root to be different across platforms
	 * @param mountPath - mount path
	 */
	protected mountAtRoot(mountPath: string): Promise<void>;
	initialize(params: InitParams): Promise<void>;
}

export {};
