name: keen_asr
description: "KeenASR SDK"
version: 0.0.1
homepage:

environment:
  sdk: ^3.7.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  web: ^1.0.0
  plugin_platform_interface: ^2.0.2

  async: ^2.12.0
  utopia_platform_utils: ^0.0.6+1
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  pigeon: ^25.3.2

flutter:
  plugin:
    platforms:
      android:
        package: com.keenresearch.keenasr.flutter
        pluginClass: KeenASRFlutterPlugin
      ios:
        pluginClass: KeenAsrPlugin
      web:
        pluginClass: KeenASRWeb
        fileName: src/web/keen_asr_web.dart
